cd $1 || exit
uv sync --no-dev
bash ./scripts/start_screen.sh tele-bookmark-bot 'uv run --no-project tele_bookmark_bot.py'
bash ./scripts/start_screen.sh hn-new-github-repos 'uv run --no-project hn_new_github_repos.py -v'
#bash ./scripts/start_screen.sh tele-furus 'uv run --no-project twitter_furus.py'
bash ./scripts/start_screen.sh tele-stock-rider-bot 'uv run --no-project tele_stock_rider_bot.py'
bash ./scripts/start_screen.sh tele-wiki-tok-bot 'uv run --no-project tele-wiki-tok-bot.py --database-file-path ~/tele_wiki_tok_bot.db -v'
#bash ./scripts/start_screen.sh tele-py-code-runner 'uv run tele_py_code_runner.py -b -v'
bash ./scripts/start_screen.sh tele-web-links 'uv run --no-project tele_web_links.py'
bash ./scripts/start_screen.sh tele-memo 'uv run --no-project tele_memo.py'
#bash ./scripts/start_screen.sh tele-github-context-builder 'uv run --no-project tele_github_context_builder.py -b -v'
bash ./scripts/start_screen.sh muninn-storage 'uv run --no-project muninn-storage.py --token-file secret-keys/token.json --database-file-path ~/rider_brain.db'
bash ./scripts/start_screen.sh muninn-web-page-downloader 'uv run --no-project muninn-web-page-downloader.py --database-file-path ~/rider_brain.db'
bash ./scripts/start_screen.sh muninn-git-repo-downloader 'uv run --no-project muninn-git-repo-downloader.py --database-file-path ~/rider_brain.db'
bash ./scripts/start_screen.sh muninn-photo-ocr 'uv run --no-project muninn-photo-ocr.py --database-file-path ~/rider_brain.db'
